apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: "rihadwork@hotmail.com"
    privateKeySecretRef:
      name: issuer
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z01423492GF3QUJP60T5L
          region: eu-west-2
      selector:
        dnsZones:
          - "networking.rihad.co.uk"
    - http01:
        ingress:
          class: nginx