FROM node@sha256:5373f1906319b3a1f291da5d102f4ce5c77ccbe29eb637f072b6c7b70443fc36 AS builder
# sha value is to utilise node:22-slim base image

WORKDIR /app

RUN corepack enable

COPY package.json yarn.lock .yarnrc.yml .

COPY .yarn .yarn

RUN yarn install

COPY . . 

RUN yarn build

RUN yarn workspaces focus --production


FROM node@sha256:e4bf2a82ad0a4037d28035ae71529873c069b13eb0455466ae0bc13363826e34 AS production
# sha value is to utilise node:22-alpine base image

RUN adduser -u 10000 -D rihad

WORKDIR /app

COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/lib /app/lib
COPY --from=builder /app/public /app/public
COPY --from=builder /app/locales /app/locales
COPY --from=builder /app/app.js /app/app.js
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/yarn.lock /app/yarn.

RUN chown -R 10000:10000 /app/public/uploads

USER rihad

EXPOSE 3000

CMD ["node", "app.js"]










