apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: threat-composer-app
  namespace: argo-cd
spec:
  project: default

  source:
    repoURL: 'https://github.com/rihad-a/eks.git'
    targetRevision: HEAD
    path: apps

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: threat-composer-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true