apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app
  labels:
    app: hedgedoc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hedgedoc
  template:
    metadata:
      labels:
        app: hedgedoc
    spec:
      securityContext:
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      containers:
        - name: hedgedoc
          image: 291759414346.dkr.ecr.eu-west-2.amazonaws.com/eks-project:latest
          ports:
            - containerPort: 3000
          env:
            - name: CMD_DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-url
                  key: CMD_DB_URL
            - name: CMD_DOMAIN
              value: "hedgedoc.networking.rihad.co.uk"
            - name: CMD_URL_ADDPORT
              value: "false"
            - name: NODE_EXTRA_CA_CERTS
              value: "/etc/ssl/certs/global-bundle.pem"
            - name: CMD_PROTOCOL_USESSL
              value: "true"
          volumeMounts:
            - name: uploads-store
              mountPath: "/public/uploads"
            - name: global-bundle-volume
              mountPath: "/etc/ssl/certs/global-bundle.pem"
              subPath: global-bundle.pem
      volumes:
        - name: uploads-store
          persistentVolumeClaim:
            claimName: efs-pvc
        - name: global-bundle-volume
          configMap:
            name: global-bundle

---
apiVersion: v1
kind: Service
metadata:
  name: argo-app
spec:
  selector:
    app: hedgedoc
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: app-port
      protocol: TCP
      port: 8080
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/cluster-issuer: "issuer"
spec:
  ingressClassName: nginx
  rules:
    - host: hedgedoc.networking.rihad.co.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argo-app
                port:
                  number: 80
  tls:
    - hosts:
        - hedgedoc.networking.rihad.co.uk
      secretName: hedgedoc-tls

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0dc2d8c33e06616af
    ## Update EFS File System ID after running Terraform Apply and finding resource in AWS

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
  namespace: hedgedoc-app
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeName: efs-pv
  resources:
    requests:
      storage: 500Mi