apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets-s3
  namespace: hedgedoc-app
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore
    kind: SecretStore
  target:
    name: s3
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: s3